StudentStoreBackend:
  StudentDeploy:
    image: v47.0
    replicaCount: 1

    resources:
      requests:
        cpu: 100m
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"

    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8084

    readinessProbe:
      httpGet:
        path: /actuator/health
        port: 8084

    startupProbe:
      httpGet:
        path: /actuator/health
        port: 8084

StudentSvc:
  svcPort: 8081
  metricsAPI: /actuator/prometheus

StudentCm:
  mysqlHost: jdbc:mysql://database.copwkqqs6nyf.us-east-1.rds.amazonaws.com:3306/datastore
  name: admin

StudentSecret:
  mysqlPassword: dmlrcmFtMjAwMQ==
