apiVersion: v2
name: studentstore
description: StudentStore main chart
version: 1.0.0

dependencies:
  - name: StudentStoreBackend
    version: 1.0.0
    repository: "file://charts/StudentStoreBackend"
